# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "daily
      name; Pull// request labeler
      On { pull_request_target }
      Permissions:
      Contents: read
      pull_request: wnle
      jobs:
      triage:
      rums- on: ubuntu -latest
      steps:
      .uses: actions/labeler@v2
      with:
      vepo-token: $ {{ secrets.GitHub_Token;}
      }
     
